---
# defaults file for kyma_infra
maven_deploy: false
app_path: .
app_name: helloworld-mdb
git_url: https://github.com/savitharaghunathan/helloworld-mdb.git
javaee_git_branch: javaee
quarkus_git_branch: quarkus
jboss_install_home: /opt/jboss-eap
jboss_owner: jboss-eap
jboss_group: jboss-eap

