---
# check if java is installed and print version usimd debug module
- name: Check if Java is installed
  ansible.builtin.command: 
    cmd: java -version
  ignore_errors: true
  register: java_output

- name: Display Java version
  debug:
    var: java_output.stdout_lines
  when: java_output.rc == 0

- name: Check if Maven is installed
  ansible.builtin.command: 
    cmd: mvn --version
  ignore_errors: true
  register: mvn_output

- name: Display Maven version
  debug:
    var: mvn_output.stdout_lines
  when: mvn_output.rc == 0

- name: when Maven is not installed
  debug:
    msg: "Maven is not installed on the target machine."
  when: mvn_output.rc != 0

# Hack: to avoid ssl certificate error
- name: Download certificate from maven.repository.redhat.com
  ansible.builtin.shell: "echo -n | openssl s_client -connect maven.repository.redhat.com:443 -servername maven.repository.redhat.com 2>/dev/null | openssl x509 > /tmp/maven_repository_redhat_com.cert"

# Hack: to avoid ssl certificate error
- name: Check if certificate is already installed
  ansible.builtin.shell: "keytool -list -alias mycert -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit"
  ignore_errors: true
  register: cert_check

- name: Import certificate into Java keystore
  ansible.builtin.shell: "keytool -import -alias mycert -keystore $JAVA_HOME/jre/lib/security/cacerts -file /tmp/maven_repository_redhat_com.cert -storepass changeit -noprompt"
  when: cert_check.rc != 0

- name: Configure jboss
  include_tasks: java-app-deploy-prereq.yml
  when: app_name is defined and app_name == "coolstoredb"

- name: Clone the Java EE application
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "/home/fedora/{{ app_name }}"
    version: "{{ javaee_git_branch }}"

- name: Deploy the application with Maven to EAP
  ansible.builtin.shell: mvn clean package 
  args:
    chdir: "{{ local_app_path }}"


- name: Check if war file is present
  ansible.builtin.stat:
    path: "{{ war_file_path }}"
  register: warfile

# print the result of war file check
- name: Display war file status
  debug:
    var: warfile.stat.exists

- name: Deploy the application with Maven to EAP
  ansible.builtin.copy:
    src: "{{ war_file_path }}"
    dest: "{{ jboss_install_home }}/deployments/"
    remote_src: yes
    owner: "{{ jboss_owner }}"
    group: "{{ jboss_group }}"
    mode: '0644'
  become: true

# todo verify url