---

# create docker db container
- name: Create docker db container
  ansible.builtin.shell: docker run --name myPostgresDb -p 5432:5432 -e POSTGRES_USER=postgresUser -e POSTGRES_PASSWORD=postgresPW -e POSTGRES_DB=postgresDB -d postgres
  become_user: fedora

- name: "JBoss EAP installation and configuration 1"
  vars:
    wildfly_install_workdir: '/opt'
    wildfly_version: '7.4.0'
    install_name: jboss-eap
    wildfly_archive_filename: "{{ install_name }}-{{ wildfly_version }}.zip"
    wildfly_user: "{{ install_name }}"
    wildfly_group: "{{ install_name }}"
    wildfly_config_base: standalone-full.xml
    wildfly_home: "{{ wildfly_install_workdir }}/{{ install_name }}-{{ 7.4 }}"
    wildfly_driver_module_name: "org.postgresql"
    wildfly_driver_version: "42.5.4"
    wildfly_driver_jar_filename: "postgresql-{{ wildfly_driver_version }}.jar"
    wildfly_driver_jar_url: "https://jdbc.postgresql.org/download/postgresql-42.5.4.jar"
  include_role:
    name: middleware_automation.wildfly.wildfly_driver

#restart jboss server
- name: Restart JBoss EAP
  ansible.builtin.service:
    name: jboss-eap
    state: restarted
  become: true

# copy files/postgres.cli to /opt/jboss-eap-7.4/bin
- name: Copy postgres.cli to /opt/jboss-eap-7.4/bin
  ansible.builtin.copy:
    src: files/postgres.cli
    dest: /opt/jboss-eap-7.4/bin
    owner: jboss-eap
    group: jboss-eap
    mode: 0644
  become: true

# copy postgres-config.sh to /opt/jboss-eap-7.4/bin
- name: Copy postgres-config.sh to /opt/jboss-eap-7.4/bin
  ansible.builtin.copy:
    src: files/postgres-config.sh
    dest: /opt/jboss-eap-7.4/bin
    owner: jboss-eap
    group: jboss-eap
    mode: 0755
  become: true

- name: Run postgres-config.sh
  ansible.builtin.shell: ./postgres-config.sh
  become: true
  args:
    chdir: /opt/jboss-eap-7.4/bin

