---
- tasks:
  - name: Install Java 11.0.21-tem
    command: "sdk install java 11.0.21-tem"

  - name: Use Java 11.0.21-tem
    command: "sdk use java 11.0.21-tem"

  - name: Check Maven version
    command: "mvn -v"
    register: maven_version

  - name: Display Maven version
    debug:
      var: maven_version.stdout_lines

  - name: Enable and start Podman socket
    command: "systemctl --user enable podman.socket --now"
    

  - name: Start Podman service
    command: "sudo service podman start"
    become: true

  - name: Check Podman service status
    command: "service podman status"

  - name: Display Podman remote socket information
    command: "podman info | grep -A2 'remoteSocket'"
    register: podman_info

  - name: Display Podman remote socket information info
    debug:
      var: podman_info.stdout_lines

  - name: Set environment variables for Podman
    ansible.builtin.lineinfile:
      path: "/home/fedora/.bashrc"
      line: |
        export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
        export TESTCONTAINERS_RYUK_DISABLED=true
  
  - name: Reload shell to apply changes
    command: "source /home/fedora/.bashrc"
    args:
      executable: /bin/bash
