---
# chdir to /home/fedora/{{app_name}}
- name: chdir to /home/fedora/{{app_name}}
  ansible.builtin.shell: cd /home/fedora/{{app_name}}
  args:
    chdir: /home/fedora/{{app_name}}


# checkout quarkus branch and track it - git checkout remotes/origin/quarkus --track
- name: checkout quarkus branch and track it
  ansible.builtin.shell: git checkout remotes/origin/{{ quarkus_git_branch }} --track
  args:
    chdir: /home/fedora/{{app_name}}

- name: Check if Docker is accessible using socket
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 10
  ignore_errors: true
  register: docker_socket_status

- name: Display Docker socket status
  ansible.builtin.debug:
    var: docker_socket_status


# build the quarkus app - mvn clean package
- name: build the quarkus app
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /home/fedora/{{app_name}}

# Run the quarkus app locally
- name: Start the server
  ansible.builtin.shell: "nohup mvn clean quarkus:dev -Dquarkus.http.port=8085 > server.log 2>&1 & echo $! > server.pid"
  args:
    chdir: /home/fedora/{{ app_name }}
  register: start_server_result

# check if quarkus process is running using pid 
# need a better way to check if quarkus app is running
- name: Check if Quarkus app is running
  ansible.builtin.shell: "ps -p $(cat server.pid) | grep -v PID"
  args:
    chdir: /home/fedora/{{ app_name }}
  register: quarkus_app_running
  until: quarkus_app_running.stdout != ""
  retries: 10
  delay: 5

