build:
  uri: https://github.com/jboss-developer/jboss-eap-quickstarts.git
  ref: EAP_7.4.0.GA
  s2i:
    jdk: "8"
    galleonLayers:
      - jaxrs-server
  env:
  - name: ARTIFACT_DIR
    value: helloworld/target
  - name: MAVEN_ARGS_APPEND
    value: -am -pl helloworld
  - name: MAVEN_OPTS
    value: '-XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m'
deploy:
  replicas: 2
