---
# tasks file for jboss-app-deploy

- name: Create /home/fedora/local directory
  file:
    path: /home/fedora/local
    state: directory
    owner: fedora
    group: fedora

- name: Copy the war  to /home/fedora/local
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/{{ app_name }}.war"
    dest: "/home/fedora/local/"
  when: warfile_deploy

- name: Deploy the application with Maven to EAP
  ansible.builtin.copy:
    src: "/home/fedora/local/{{ app_name }}.war"
    dest: "{{ jboss_install_home }}/deployments/"
    remote_src: yes
    owner: "{{ jboss_owner }}"
    group: "{{ jboss_group }}"
    mode: '0644'
  when: warfile_deploy
  become: true

- name: Sleep for 60 seconds to allow deployment to be complete
  ansible.builtin.wait_for:
    timeout: 60
  delegate_to: localhost

- name: "Verify if the app is deployed and accessible."
  become: true
  vars:
    ports: '8080'
  ansible.builtin.get_url:
    url: "http://localhost:{{ ports }}/{{ app_name }}/HelloWorld"
    dest: "/tmp/{{ ports }}"

- name: Display localhost:8080 content
  shell: "cat /tmp/8080"
  register: out

- name: "INFO: Display localhost:8080 content"
  debug: var=out.stdout_lines
