---

- name: Create /home/fedora/local directory
  file:
    path: /home/fedora/local
    state: directory
    owner: fedora
    group: fedora

- name: Check local path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost


- name: Copy the war  to /home/fedora/local
  ansible.builtin.synchronize:
    src: "{{ local_path.stat.path }}/{{ app_name }}.war"
    dest: "/home/fedora/local/"
  when: warfile_deploy


- name: Deploy the application with Maven to EAP
  ansible.builtin.copy:
    src: "/home/fedora/local/{{ app_name }}.war"
    dest: "/opt/wildfly/deployments/"
    remote_src: yes
    owner: wildfly
    group: wildfly
    mode: '0644'
  when: warfile_deploy
  become: true

- name: "Verify if the app is deployed and accessible."
  become: true
  vars:
    ports: '8080'
  ansible.builtin.get_url:
    url: "http://localhost:{{ ports }}/{{ app_name }}/HelloWorld"
    dest: "/tmp/{{ ports }}"

- name: Display localhost:8080 content
  shell: "cat /tmp/8080"
  register: out

- name: "INFO: Display localhost:8080 content"
  debug: var=out.stdout_lines
